from __future__ import annotations

import json

from pathlib import Path

import pytest

import autoclanker.bigbets as autoclanker_bigbets

from autoclanker.cli import main as autoclanker_main
from bigbets import (
    BIGBETS_ARTIFACT_SCHEMA_VERSION,
    BIGBETS_REGISTRY_SCHEMA_VERSION,
    BIGBETS_SITE_SCHEMA_VERSION,
    BIGBETS_VERSION,
    ValidationFailure,
    load_bigbets_registry,
    registry_to_input_payload,
    render_bigbets,
    validate_bigbets_registry,
)
from bigbets.cli import main as bigbets_main
from bigbets.site import list_storage_adapters, write_static_site
from tests.compliance import covers

ROOT = Path(__file__).resolve().parents[1]
EXAMPLE = ROOT / "examples" / "bigbets" / "basic_portfolio.yaml"


@covers("M8-001")
def test_bigbets_registry_validates_and_renders_core_artifacts() -> None:
    registry = load_bigbets_registry(EXAMPLE)
    rendered = render_bigbets(registry)

    normalized = json.loads(rendered.registry_json)
    assert normalized["schema_version"] == BIGBETS_REGISTRY_SCHEMA_VERSION
    assert normalized["artifact_schema_version"] == BIGBETS_ARTIFACT_SCHEMA_VERSION
    assert normalized["generator"]["name"] == "bigbets"
    assert normalized["generator"]["version"] == BIGBETS_VERSION
    assert normalized["summary"]["big_bet_count"] == 3
    assert normalized["summary"]["idea_family_count"] == 3
    assert normalized["summary"]["p0_big_bet_count"] == 2
    assert (
        registry_to_input_payload(registry)["schema_version"]
        == BIGBETS_REGISTRY_SCHEMA_VERSION
    )
    assert "data_plane_batching" in rendered.mermaid
    assert f"schema_version={BIGBETS_REGISTRY_SCHEMA_VERSION}" in rendered.mermaid
    excalidraw = json.loads(rendered.excalidraw)
    assert excalidraw["type"] == "excalidraw"
    assert excalidraw["source"] == f"bigbets {BIGBETS_VERSION}"
    assert "<svg" in rendered.svg
    assert "data-bet-id" in rendered.svg
    assert "bigbets-registry-schema-version" in rendered.html
    assert f"Generated by <code>bigbets {BIGBETS_VERSION}</code>" in rendered.html
    assert (
        "kind,big_bet_priority,big_bet_order,wave,big_bet_id" in rendered.rankings_csv
    )
    assert "schema_version,generator_version" in rendered.rankings_csv
    assert "# Example Big Bets Portfolio" in rendered.markdown
    assert f"Generated by `bigbets {BIGBETS_VERSION}`." in rendered.markdown
    assert f"Registry schema: `{BIGBETS_REGISTRY_SCHEMA_VERSION}`." in rendered.markdown
    assert autoclanker_bigbets.render_bigbets(registry).mermaid == rendered.mermaid
    assert autoclanker_bigbets.BIGBETS_VERSION == BIGBETS_VERSION


@covers("M8-001")
def test_bigbets_standalone_and_autoclanker_alias_cli(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    assert bigbets_main(["validate", "--input", str(EXAMPLE)]) == 0
    validate_payload = json.loads(capsys.readouterr().out)
    assert validate_payload["schema_version"] == BIGBETS_REGISTRY_SCHEMA_VERSION
    assert (
        validate_payload["artifact_schema_version"] == BIGBETS_ARTIFACT_SCHEMA_VERSION
    )
    assert validate_payload["generator"]["version"] == BIGBETS_VERSION
    assert validate_payload["summary"]["big_bet_count"] == 3

    with pytest.raises(SystemExit) as bigbets_version:
        bigbets_main(["--version"])
    assert bigbets_version.value.code == 0
    assert BIGBETS_VERSION in capsys.readouterr().out

    with pytest.raises(SystemExit) as alias_version:
        autoclanker_main(["bigbets", "--version"])
    assert alias_version.value.code == 0
    assert BIGBETS_VERSION in capsys.readouterr().out

    output_dir = tmp_path / "site"
    assert (
        autoclanker_main(
            [
                "bigbets",
                "render",
                "--input",
                str(EXAMPLE),
                "--output-dir",
                str(output_dir),
            ]
        )
        == 0
    )
    render_payload = json.loads(capsys.readouterr().out)
    assert render_payload["tool"] == "bigbets_render"
    assert render_payload["schema_version"] == BIGBETS_REGISTRY_SCHEMA_VERSION
    assert render_payload["artifact_schema_version"] == BIGBETS_ARTIFACT_SCHEMA_VERSION
    assert render_payload["generator"]["version"] == BIGBETS_VERSION
    assert (output_dir / "index.html").exists()
    assert (output_dir / "big_bets.registry.json").exists()
    assert (output_dir / "big_bets.excalidraw").exists()
    artifact_metadata = json.loads(
        (output_dir / "big_bets.artifact_metadata.json").read_text(encoding="utf-8")
    )
    assert artifact_metadata["schema_version"] == BIGBETS_REGISTRY_SCHEMA_VERSION
    assert (
        artifact_metadata["artifact_schema_version"] == BIGBETS_ARTIFACT_SCHEMA_VERSION
    )
    assert artifact_metadata["generator"]["version"] == BIGBETS_VERSION

    assert bigbets_main(["emit", "--input", str(EXAMPLE), "--format", "mermaid"]) == 0
    assert "flowchart TD" in capsys.readouterr().out
    assert (
        bigbets_main(["emit", "--input", str(EXAMPLE), "--format", "excalidraw"]) == 0
    )
    assert '"type": "excalidraw"' in capsys.readouterr().out
    assert bigbets_main(["emit", "--input", str(EXAMPLE), "--format", "metadata"]) == 0
    assert BIGBETS_ARTIFACT_SCHEMA_VERSION in capsys.readouterr().out


@covers("M8-001")
def test_bigbets_site_scaffold_writes_editable_static_app(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    registry = load_bigbets_registry(EXAMPLE)
    scaffold = write_static_site(
        registry,
        tmp_path / "manual-site",
        app_id="weekly-bigbets",
    )
    assert (scaffold.output_dir / "index.html").exists()
    assert (scaffold.output_dir / "registry.seed.json").exists()
    assert (scaffold.output_dir / "big_bets.artifact_metadata.json").exists()
    assert (scaffold.output_dir / "app.js").exists()
    assert (scaffold.output_dir / "Excalifont-Regular.woff2").exists()
    assert (scaffold.output_dir / "storage-adapter.js").exists()
    assert scaffold.site_schema_version == BIGBETS_SITE_SCHEMA_VERSION
    seed = json.loads(
        (scaffold.output_dir / "registry.seed.json").read_text(encoding="utf-8")
    )
    assert seed["schema_version"] == BIGBETS_REGISTRY_SCHEMA_VERSION
    site_artifact_metadata = json.loads(
        (scaffold.output_dir / "big_bets.artifact_metadata.json").read_text(
            encoding="utf-8"
        )
    )
    assert site_artifact_metadata["site_schema_version"] == BIGBETS_SITE_SCHEMA_VERSION
    index_html = (scaffold.output_dir / "index.html").read_text(encoding="utf-8")
    app_js = (scaffold.output_dir / "app.js").read_text(encoding="utf-8")
    site_md = (scaffold.output_dir / "SITE.md").read_text(encoding="utf-8")
    assert "window.bigbetsStorageAdapter" in index_html
    assert "bigbets-site-schema-version" in index_html
    assert "Dependency board" in index_html
    assert "Idea-family sheet" in index_html
    assert "Snapshot" in index_html
    assert "Priority layers" in index_html
    assert "localStorageAdapter" in app_js
    assert "REGISTRY_SCHEMA_VERSION" in app_js
    assert "artifactMetadataJson" in app_js
    assert "generator_version" in app_js
    assert "renderExcalidraw" in app_js
    assert "fontFamily: 5" in app_js
    assert "saveSnapshot" in app_js
    assert 'draggable="true"' in app_js
    assert 'contenteditable="true"' in app_js
    assert "fetchIssue" in (scaffold.output_dir / "storage-adapter.js").read_text(
        encoding="utf-8"
    )
    assert "listSnapshots" in (scaffold.output_dir / "storage-adapter.js").read_text(
        encoding="utf-8"
    )
    assert "site schema" in site_md.lower()
    assert "writeArtifacts" in app_js
    assert "/client/" not in index_html
    assert ".db.collection" not in app_js
    assert ".fs.write" not in app_js

    output_dir = tmp_path / "cli-site"
    assert (
        bigbets_main(
            [
                "site",
                "scaffold",
                "--input",
                str(EXAMPLE),
                "--output-dir",
                str(output_dir),
                "--app-id",
                "weekly-bigbets",
            ]
        )
        == 0
    )
    payload = json.loads(capsys.readouterr().out)
    assert payload["tool"] == "bigbets_site_scaffold"
    assert payload["app_id"] == "weekly-bigbets"
    assert payload["site_schema_version"] == BIGBETS_SITE_SCHEMA_VERSION
    assert (output_dir / "big_bets.svg").exists()
    assert (output_dir / "big_bets.excalidraw").exists()


@covers("M8-001")
def test_bigbets_site_storage_adapter_registry(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    assert {adapter.name for adapter in list_storage_adapters()} == {
        "local-storage",
        "none",
    }

    assert bigbets_main(["site", "adapters"]) == 0
    payload = json.loads(capsys.readouterr().out)
    assert payload["tool"] == "bigbets_site_adapters"
    assert {adapter["name"] for adapter in payload["adapters"]} == {
        "local-storage",
        "none",
    }

    custom_adapter = tmp_path / "custom-storage-adapter.js"
    custom_adapter.write_text(
        "window.bigbetsStorageAdapter = { name: 'custom' };\n",
        encoding="utf-8",
    )
    output_dir = tmp_path / "custom-site"
    assert (
        bigbets_main(
            [
                "site",
                "scaffold",
                "--input",
                str(EXAMPLE),
                "--output-dir",
                str(output_dir),
                "--storage-adapter-file",
                str(custom_adapter),
            ]
        )
        == 0
    )
    payload = json.loads(capsys.readouterr().out)
    assert payload["storage_adapter"] == str(custom_adapter)
    assert (output_dir / "storage-adapter.js").read_text(
        encoding="utf-8"
    ) == "window.bigbetsStorageAdapter = { name: 'custom' };\n"

    replacement_adapter = tmp_path / "replacement-storage-adapter.js"
    replacement_adapter.write_text(
        "window.bigbetsStorageAdapter = { name: 'replacement' };\n",
        encoding="utf-8",
    )
    assert (
        bigbets_main(
            [
                "site",
                "scaffold",
                "--input",
                str(EXAMPLE),
                "--output-dir",
                str(output_dir),
                "--storage-adapter-file",
                str(replacement_adapter),
            ]
        )
        == 0
    )
    preserved_payload = json.loads(capsys.readouterr().out)
    assert preserved_payload["storage_adapter"].startswith("existing:")
    assert (output_dir / "storage-adapter.js").read_text(
        encoding="utf-8"
    ) == "window.bigbetsStorageAdapter = { name: 'custom' };\n"

    output_dir_none = tmp_path / "no-adapter-site"
    assert (
        bigbets_main(
            [
                "site",
                "scaffold",
                "--input",
                str(EXAMPLE),
                "--output-dir",
                str(output_dir_none),
                "--storage-adapter",
                "none",
            ]
        )
        == 0
    )
    assert not (output_dir_none / "storage-adapter.js").exists()


@covers("M8-001")
def test_bigbets_snapshot_cli_writes_dated_snapshot(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    output_dir = tmp_path / "site"
    assert (
        bigbets_main(
            [
                "snapshot",
                "create",
                "--input",
                str(EXAMPLE),
                "--output-dir",
                str(output_dir),
                "--name",
                "Weekly plan",
            ]
        )
        == 0
    )
    payload = json.loads(capsys.readouterr().out)
    assert payload["tool"] == "bigbets_snapshot_create"
    assert payload["snapshot"]["name"] == "Weekly plan"
    snapshot_path = Path(payload["snapshot_path"])
    assert snapshot_path.exists()
    snapshot_registry = json.loads(snapshot_path.read_text(encoding="utf-8"))
    assert snapshot_registry["schema_version"] == BIGBETS_REGISTRY_SCHEMA_VERSION
    index_path = output_dir / "snapshots" / "index.json"
    assert index_path.exists()

    assert bigbets_main(["snapshot", "list", "--output-dir", str(output_dir)]) == 0
    list_payload = json.loads(capsys.readouterr().out)
    assert list_payload["tool"] == "bigbets_snapshot_list"
    assert list_payload["snapshots"][0]["name"] == "Weekly plan"


@covers("M8-001")
def test_bigbets_rejects_unknown_explicit_schema_version() -> None:
    payload: dict[str, object] = {
        "schema_version": "bigbets.registry.v999",
        "big_bets": [],
        "idea_families": [],
    }

    with pytest.raises(ValidationFailure, match="unsupported schema_version"):
        validate_bigbets_registry(payload)


@covers("M8-001")
def test_bigbets_rejects_ambiguous_wave_priority_and_roles() -> None:
    payload = registry_to_input_payload(load_bigbets_registry(EXAMPLE))
    assert isinstance(payload["big_bets"], list)
    assert isinstance(payload["idea_families"], list)

    bad_priority = json.loads(json.dumps(payload))
    bad_priority["big_bets"][0]["priority"] = "P2"
    with pytest.raises(ValidationFailure, match="wave 1 requires 'P0'"):
        validate_bigbets_registry(bad_priority)

    bad_role = json.loads(json.dumps(payload))
    bad_role["idea_families"][0]["role"] = "custom-label"
    with pytest.raises(ValidationFailure, match="unsupported role"):
        validate_bigbets_registry(bad_role)
