"""Compatibility shim over the split analysis engine.

The implementation lives in dedicated modules — `patterns` (path/regex/library
matching), `categorize` (the runtime categorization engine), `targets`,
`slices`, and `scopes` (boundary decomposition). Import from those modules in
new code; this shim preserves the historical `clankerprof.analysis` surface.
"""

from __future__ import annotations

from clankerprof.categorize import (
    categorize_frame,
    categorize_ruby_frame,
    categorize_runtime_frame,
    extract_gem_name,
    is_ruby_stdlib_path,
    load_default_ruby_core_classes,
    load_ruby_core_classes,
    ruby_rules,
    runtime_rules_from_file,
    simplify_category,
)
from clankerprof.patterns import (
    DEFAULT_LIBRARY_SELECTORS,
    DEFAULT_RUNTIME_RULES,
    JsonValue,
    LibraryPath,
    LibrarySelector,
    PatternMode,
    extract_library_name,
    extract_library_path,
    format_time,
    is_gc_function,
    is_runtime_stdlib_path,
    match_category_pattern,
    match_path_pattern,
    match_regex,
)
from clankerprof.rules import RuntimeRuleSet
from clankerprof.scopes import (
    BoundaryAnalysisOptions,
    BoundaryAnalysisResult,
    BoundaryCategoryDefinition,
    BoundaryCountMode,
    BoundaryDefinition,
    BoundaryDomainDefinition,
    BoundaryStats,
    FramePredicate,
    FramePredicateExpr,
    FramePredicateInput,
    analyze_boundaries,
    analyze_boundary_facts,
    frame_predicate_expr,
    frame_predicate_expr_leaf_predicates,
    normalize_frame_predicate_expr,
    parse_frame_predicate,
    parse_frame_predicates,
)
from clankerprof.slices import (
    GC_PSEUDO_SLICE,
    UNCOLLAPSIBLE_PSEUDO_SLICE,
    AttributionRule,
    SliceAnalysisOptions,
    SliceAnalysisResult,
    SliceDefinition,
    SliceFrameStats,
    SliceStats,
    analyze_slice_facts,
    analyze_slices,
)
from clankerprof.targets import (
    OutputMode,
    TargetAnalysisOptions,
    analyze_target_facts,
    analyze_targets,
    load_json_mapping,
)

__all__ = [
    "DEFAULT_LIBRARY_SELECTORS",
    "DEFAULT_RUNTIME_RULES",
    "GC_PSEUDO_SLICE",
    "UNCOLLAPSIBLE_PSEUDO_SLICE",
    "AttributionRule",
    "BoundaryAnalysisOptions",
    "BoundaryAnalysisResult",
    "BoundaryCategoryDefinition",
    "BoundaryCountMode",
    "BoundaryDefinition",
    "BoundaryDomainDefinition",
    "BoundaryStats",
    "FramePredicate",
    "FramePredicateExpr",
    "FramePredicateInput",
    "JsonValue",
    "LibraryPath",
    "LibrarySelector",
    "OutputMode",
    "PatternMode",
    "RuntimeRuleSet",
    "SliceAnalysisOptions",
    "SliceAnalysisResult",
    "SliceDefinition",
    "SliceFrameStats",
    "SliceStats",
    "TargetAnalysisOptions",
    "analyze_boundaries",
    "analyze_boundary_facts",
    "analyze_slice_facts",
    "analyze_slices",
    "analyze_target_facts",
    "analyze_targets",
    "categorize_frame",
    "categorize_ruby_frame",
    "categorize_runtime_frame",
    "extract_gem_name",
    "extract_library_name",
    "extract_library_path",
    "format_time",
    "frame_predicate_expr",
    "frame_predicate_expr_leaf_predicates",
    "is_gc_function",
    "is_ruby_stdlib_path",
    "is_runtime_stdlib_path",
    "load_default_ruby_core_classes",
    "load_json_mapping",
    "load_ruby_core_classes",
    "match_category_pattern",
    "match_path_pattern",
    "match_regex",
    "normalize_frame_predicate_expr",
    "parse_frame_predicate",
    "parse_frame_predicates",
    "ruby_rules",
    "runtime_rules_from_file",
    "simplify_category",
]
