from __future__ import annotations

from bigbets.core import (
    BigBet,
    BigBetsRegistry,
    IdeaFamily,
    JsonValue,
    RenderedBigBets,
    ValidationFailure,
    load_bigbets_registry,
    load_serialized_payload,
    load_serialized_payload_from_text,
    normalize_bigbets_registry,
    registry_to_input_payload,
    render_artifact_metadata_json,
    render_bigbets,
    render_excalidraw,
    render_html,
    render_markdown,
    render_mermaid,
    render_rankings_csv,
    render_svg,
    to_json_value,
    validate_bigbets_registry,
    write_bigbets_artifacts,
)
from bigbets.site import (
    StaticSiteScaffold,
    StorageAdapter,
    list_storage_adapters,
    write_static_site,
)
from bigbets.version import (
    BIGBETS_ARTIFACT_SCHEMA_VERSION,
    BIGBETS_GENERATOR_NAME,
    BIGBETS_REGISTRY_SCHEMA_VERSION,
    BIGBETS_SITE_SCHEMA_VERSION,
    BIGBETS_VERSION,
    generator_metadata,
)

__version__ = BIGBETS_VERSION

__all__ = [
    "BIGBETS_ARTIFACT_SCHEMA_VERSION",
    "BIGBETS_GENERATOR_NAME",
    "BIGBETS_REGISTRY_SCHEMA_VERSION",
    "BIGBETS_SITE_SCHEMA_VERSION",
    "BIGBETS_VERSION",
    "BigBet",
    "BigBetsRegistry",
    "IdeaFamily",
    "JsonValue",
    "RenderedBigBets",
    "StaticSiteScaffold",
    "StorageAdapter",
    "ValidationFailure",
    "load_bigbets_registry",
    "load_serialized_payload",
    "load_serialized_payload_from_text",
    "list_storage_adapters",
    "normalize_bigbets_registry",
    "registry_to_input_payload",
    "render_artifact_metadata_json",
    "render_bigbets",
    "render_excalidraw",
    "render_html",
    "render_markdown",
    "render_mermaid",
    "render_rankings_csv",
    "render_svg",
    "to_json_value",
    "validate_bigbets_registry",
    "generator_metadata",
    "write_bigbets_artifacts",
    "write_static_site",
    "__version__",
]
